services:
  postgres:
    image: postgres:16-alpine
    container_name: booking_tour_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking_tour
    ports:
      - '5433:5432'
    volumes:
      - booking_tour_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: booking_tour_redis
    restart: unless-stopped
    ports:
      - '6380:6379'
    volumes:
      - booking_tour_redisdata:/data

volumes:
  booking_tour_pgdata:
  booking_tour_redisdata:
